language: python
cache: pip

python:
  #  - 'pypy3'
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - pip install -r dev-requirements.txt
  - pip install pip-tools
  - pip-compile

script: make test
