version: '3.7'

services:
  django:
    environment:
      - UPTRACE_DSN
    build:
      dockerfile: $PWD/Dockerfile
      context: ../..
    ports:
      - '8000:8000'
    command:
      - 'make'
      - 'run'
    #    networks:
    #      - example
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_HOST_AUTH_METHOD: trust
#    networks:
#      - example

#networks:
#  example:
