version: '3.7'

services:
  flask:
    environment:
      - UPTRACE_DSN
    build:
      dockerfile: $PWD/Dockerfile
      context: ../..
    ports:
      - '8000:8000'
    command:
      - 'make'
      - 'run'
