version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
    volumes:
      - 'pg_data:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'

volumes:
  pg_data:
